apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-dev-components
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:seu-usuario/infra.git'
    targetRevision: main
    path: dev/components
  destination:
    server: 'https://<DEV-EKS-ENDPOINT>'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-stage-components
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:seu-usuario/infra.git'
    targetRevision: main
    path: stage/components
  destination:
    server: 'https://<STAGE-EKS-ENDPOINT>'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-prod-components
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:seu-usuario/infra.git'
    targetRevision: main
    path: prod/components
  destination:
    server: 'https://<PROD-EKS-ENDPOINT>'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true