name: Terraform CI/CD

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente (ex: system-a/dev)"
        required: true
        type: string
        default: "system-a/dev"
      action:
        description: "Ação"
        required: true
        type: choice
        options:
          - plan
          - apply

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/infra-runner:latest

    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: terraform fmt -check -recursive || true

      - name: Lint
        run: tflint --recursive

  plan:
    name: Plan
    needs: lint
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/infra-runner:latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Validate
        run: terragrunt run-all validate --terragrunt-working-dir system-a/dev --terragrunt-non-interactive 2>&1

      - name: Plan
        run: terragrunt run-all plan --terragrunt-working-dir system-a/dev --terragrunt-non-interactive 2>&1

  apply:
    name: "${{ github.event.inputs.action }}: ${{ github.event.inputs.environment }}"
    needs: lint
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/infra-runner:latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Validate
        run: terragrunt run-all validate --terragrunt-working-dir "${{ github.event.inputs.environment }}" --terragrunt-non-interactive 2>&1

      - name: Run
        run: |
          ACTION="${{ github.event.inputs.action }}"
          APPROVE=$( [ "$ACTION" = "apply" ] && echo "--auto-approve" )
          terragrunt run-all $ACTION $APPROVE --terragrunt-working-dir "${{ github.event.inputs.environment }}" --terragrunt-non-interactive 2>&1
