
name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        type: choice
        options:
          - lint
          - plan
          - apply

jobs:
  lint:
    if: ${{ github.event.inputs.action == 'lint' }}
    runs-on: ubuntu-latest

    # usa a imagem criada no workflow build-runner
    container:
      image: ghcr.io/${{ github.repository }}/infra-runner:latest

    steps:
      # baixa o repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # # autenticação AWS via OIDC
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::123456789012:role/github-actions-role
      #     aws-region: us-east-1

      - name: Terraform init
        run: terraform init -backend=false

      # checa formatação
      - name: Terraform Format
        run: terraform fmt -check -recursive || true

      # valida código terraform
      - name: Terraform Validate
        run: terraform validate

      # inicializa regras do tflint
      - name: TFLint Init
        run: tflint --init

      # lint terraform
      - name: TFLint Scan
        run: tflint --chdir=system-a --recursive

      # # security scan tfsec
      # - name: tfsec scan
      #   run: tfsec .

      # # plan em pull requests
      # - name: Terragrunt Plan
      #   if: github.event_name == 'pull_request'
      #   run: terragrunt run-all plan

  plan:
    needs: lint
    if: ${{ github.event.inputs.action == 'plan' }}
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}/infra-runner:latest

    outputs:
      plan-path: terraform.tfplan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # exemplo OIDC (se quiser ativar depois)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/github-actions-role #exemplo
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform.tfplan

  apply:
    needs: plan
    if: ${{ github.event.inputs.action == 'apply' }}
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}/infra-runner:latest

    environment: prod 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve